# Generated by Django 2.0.3 on 2018-03-28 08:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20180328_0003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='award',
            name='date_received',
        ),
        migrations.RemoveField(
            model_name='education',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='education',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='start_date',
        ),
        migrations.AddField(
            model_name='education',
            name='end_year',
            field=models.CharField(max_length=4, null=True, validators=[django.core.validators.MinLengthValidator(4)]),
        ),
        migrations.AddField(
            model_name='education',
            name='start_year',
            field=models.CharField(max_length=4, null=True, validators=[django.core.validators.MinLengthValidator(4)]),
        ),
        migrations.AddField(
            model_name='experience',
            name='end_year',
            field=models.CharField(max_length=4, null=True, validators=[django.core.validators.MinLengthValidator(4)]),
        ),
        migrations.AddField(
            model_name='experience',
            name='start_year',
            field=models.CharField(max_length=4, null=True, validators=[django.core.validators.MinLengthValidator(4)]),
        ),
    ]
