# Generated by Django 2.0.3 on 2018-03-28 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_auto_20180328_0124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='city',
        ),
        migrations.RemoveField(
            model_name='education',
            name='country',
        ),
        migrations.RemoveField(
            model_name='education',
            name='state',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='city',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='country',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='state',
        ),
    ]
