# Generated by Django 2.0.3 on 2018-03-28 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_auto_20180328_0139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='place',
            new_name='school',
        ),
        migrations.RenameField(
            model_name='experience',
            old_name='place',
            new_name='company',
        ),
    ]
