# Generated by Django 2.0.3 on 2018-03-28 09:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_auto_20180328_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='end_year',
            field=models.CharField(blank=True, max_length=4, null=True, validators=[django.core.validators.MinLengthValidator(4)]),
        ),
        migrations.AlterField(
            model_name='experience',
            name='end_year',
            field=models.CharField(blank=True, max_length=4, null=True, validators=[django.core.validators.MinLengthValidator(4)]),
        ),
    ]
