# Generated by Django 2.0.3 on 2018-03-28 10:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_auto_20180328_0257'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='year',
            field=models.CharField(max_length=4, null=True, validators=[django.core.validators.MinLengthValidator(4)]),
        ),
    ]
